spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mjh
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: majinhao
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

